# CustomKitAddon Configuration
# Custom Kit addon for StrikePractice - Item Selection Only

# GUI Settings
gui:
  title: "&8Custom Kit Items - Page %page%"
  items-per-page: 45  # Max items per page (excluding bottom navigation row)

# Settings
settings:
  debug: true  # Enable for troubleshooting
  rename-timeout: 30  # Seconds before rename times out
  sounds:
    enabled: true
    select: "ENTITY_EXPERIENCE_ORB_PICKUP"

# ELO Settings
elo:
  fixated-elo: true  # Enable fixed ELO changes
  elo-change: 91     # Amount of ELO to add/subtract (winner gets +, loser gets -)

# Messages
messages:
  no-permission: "&cYou don't have permission to use this!"
  item-selected: "&aSelected &e%item% &afor your custom kit!"
  error-applying-item: "&cFailed to apply item to your kit!"
  rename-prompt: "&aType the new kit name in chat (supports color codes with &):"
  rename-cancel-info: "&7Type &ccancel &7to cancel the rename process."
  rename-timeout: "&cRename timed out!"
  rename-cancelled: "&cRename cancelled!"
  rename-too-long: "&cKit name is too long! Maximum 32 characters."
  rename-success: "&aKit renamed to: &f%name%"
  rename-error: "&cFailed to rename kit! Make sure you have a custom kit selected."