name: CustomKitAddon
version: ${project.version}
main: com.strikepractice.customkitaddon.CustomKitAddon
author: [Skaian+AI, destiall]
description: Advanced Custom Kit addon for StrikePractice
api-version: '1.21'
softdepend: [StrikePractice]

commands:
  customkitadmin:
    description: Admin commands for CustomKit
    permission: customkit.admin
    aliases: [cka]
    usage: /<command> <add|reload>
  ckdebug:
    description: Debug command for StrikePractice API
    permission: customkit.admin
    usage: /<command>

permissions:
  customkit.use:
    description: Allows using the custom kit GUI
    default: op
  customkit.admin:
    description: All admin permissions
    default: op
    children:
      customkit.admin.add: true
      customkit.admin.reload: true
      customkit.admin.debug: true
  customkit.admin.add:
    description: Add items to custom kit pages
    default: op
  customkit.admin.reload:
    description: Reload configuration files
    default: op
  customkit.admin.debug:
    description: Use debug commands
    default: op